---
- name: homebrewをアップデート
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: homebrewで各種パッケージをインストール
  homebrew:
    name: "{{ item }}"
  with_items:
    - ansible
    - jq
    - md5sha1sum
    - mosh
    - pwgen
    - sipcalc
    - tmux
    - tree
    - watch

- name: homebrew caskで各種パッケージをインストール
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - google-chrome
    - java
    - nmap
    - teamviewer
    - wireshark
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications

