---
- name: 再ログイン時にウィンドウを再度開く ためのキャッシュファイルを削除するスクリプトを配置
  become: yes
  copy:
    src: restore_window/disable_restore_window.sh
    dest: /usr/local/bin/disable_restore_window.sh
    mode: 0755
    owner: "{{ ansible_ssh_user }}"
    group: admin

- name: 自動ログインを設定
  become: yes
  osx_defaults:
    domain: com.apple.loginwindow
    key: LoginHook
    type: string
    value: /usr/local/bin/disable_restore_window.sh

